/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.dataController;
import dataModel.Journey;
import dataModel.Route;
import dataModel.Station;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import main.sim;

/**
 *
 * @author mstanford
 */
public class CurrentJourney extends javax.swing.JFrame {
Station departureStation;
Station arrivalStation;
Station previousStation;
Station nextStation;
Station selectedStation;
    /**
     * Creates new form Home
     */
    public CurrentJourney() {
        initComponents();
        getContentPane().setBackground(Color.WHITE); 
        departurePanel.addMouseListener(new BoxListener());
        nextPanel.addMouseListener(new BoxListener());
        arrivePanel.addMouseListener(new BoxListener());
        lastPanel.addMouseListener (new BoxListener());
            

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stopsPanel = new javax.swing.JPanel();
        departLabel = new javax.swing.JLabel();
        departurePanel = new javax.swing.JPanel();
        departLocateLabel = new javax.swing.JLabel();
        arrivalLabel = new javax.swing.JLabel();
        arrivePanel = new javax.swing.JPanel();
        arriveLocateLabel = new javax.swing.JLabel();
        lastLabel = new javax.swing.JLabel();
        lastPanel = new javax.swing.JPanel();
        lastLocateLabel = new javax.swing.JLabel();
        nextLabel = new javax.swing.JLabel();
        nextPanel = new javax.swing.JPanel();
        nextLocateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectedStopPanel = new javax.swing.JPanel();
        selectedStopLabel = new javax.swing.JLabel();
        selectedLocateLabel1 = new javax.swing.JLabel();
        selectedStopLabel1 = new javax.swing.JLabel();
        selectedLocateLabel2 = new javax.swing.JLabel();
        searchStopsTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        departureTimeLabel = new javax.swing.JLabel();
        selectedStopLabel3 = new javax.swing.JLabel();
        selectedStopLabel4 = new javax.swing.JLabel();
        arrivalTimeLabel = new javax.swing.JLabel();
        selectedLocateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        stopsPanel.setBackground(new java.awt.Color(0, 52, 102));

        departLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        departLabel.setForeground(new java.awt.Color(255, 255, 255));
        departLabel.setText("Departure");

        departurePanel.setBackground(new java.awt.Color(255, 255, 255));

        departLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        departLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        departLocateLabel.setText("Location");
        departLocateLabel.setToolTipText("");

        javax.swing.GroupLayout departurePanelLayout = new javax.swing.GroupLayout(departurePanel);
        departurePanel.setLayout(departurePanelLayout);
        departurePanelLayout.setHorizontalGroup(
            departurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, departurePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(departLocateLabel)
                .addContainerGap())
        );
        departurePanelLayout.setVerticalGroup(
            departurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departurePanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(departLocateLabel)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        arrivalLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        arrivalLabel.setForeground(new java.awt.Color(255, 255, 255));
        arrivalLabel.setText("Arrival");

        arrivePanel.setBackground(new java.awt.Color(255, 255, 255));
        arrivePanel.setPreferredSize(new java.awt.Dimension(150, 150));

        arriveLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        arriveLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        arriveLocateLabel.setText("Location");
        arriveLocateLabel.setToolTipText("");
        arriveLocateLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        arriveLocateLabel.setFocusable(false);
        arriveLocateLabel.setInheritsPopupMenu(false);

        javax.swing.GroupLayout arrivePanelLayout = new javax.swing.GroupLayout(arrivePanel);
        arrivePanel.setLayout(arrivePanelLayout);
        arrivePanelLayout.setHorizontalGroup(
            arrivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arriveLocateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        arrivePanelLayout.setVerticalGroup(
            arrivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arrivePanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(arriveLocateLabel)
                .addGap(51, 51, 51))
        );

        lastLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lastLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastLabel.setText("Previous");

        lastPanel.setBackground(new java.awt.Color(255, 255, 255));
        lastPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        lastLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lastLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        lastLocateLabel.setText("Location");
        lastLocateLabel.setToolTipText("");

        javax.swing.GroupLayout lastPanelLayout = new javax.swing.GroupLayout(lastPanel);
        lastPanel.setLayout(lastPanelLayout);
        lastPanelLayout.setHorizontalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastLocateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lastPanelLayout.setVerticalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastPanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(lastLocateLabel)
                .addGap(51, 51, 51))
        );

        nextLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nextLabel.setForeground(new java.awt.Color(255, 255, 255));
        nextLabel.setText("Next");

        nextPanel.setBackground(new java.awt.Color(255, 255, 255));
        nextPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        nextLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nextLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        nextLocateLabel.setText("Location");
        nextLocateLabel.setToolTipText("");

        javax.swing.GroupLayout nextPanelLayout = new javax.swing.GroupLayout(nextPanel);
        nextPanel.setLayout(nextPanelLayout);
        nextPanelLayout.setHorizontalGroup(
            nextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nextLocateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nextPanelLayout.setVerticalGroup(
            nextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextPanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(nextLocateLabel)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout stopsPanelLayout = new javax.swing.GroupLayout(stopsPanel);
        stopsPanel.setLayout(stopsPanelLayout);
        stopsPanelLayout.setHorizontalGroup(
            stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departurePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastLabel)
                    .addComponent(departLabel)
                    .addComponent(lastPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalLabel)
                    .addComponent(arrivePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextLabel))
                .addGap(30, 30, Short.MAX_VALUE))
        );
        stopsPanelLayout.setVerticalGroup(
            stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departLabel)
                            .addComponent(arrivalLabel))
                        .addGap(7, 7, 7)
                        .addComponent(departurePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(arrivePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastLabel)
                    .addComponent(nextLabel))
                .addGap(18, 18, 18)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        departurePanel.getAccessibleContext().setAccessibleName("Depart");
        arrivePanel.getAccessibleContext().setAccessibleName("Arrive");
        lastPanel.getAccessibleContext().setAccessibleName("Last");
        nextPanel.getAccessibleContext().setAccessibleName("Next");

        selectedStopPanel.setBackground(new java.awt.Color(0, 52, 102));

        selectedStopLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedStopLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectedStopLabel.setText("Stop Num:");

        selectedLocateLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedLocateLabel1.setForeground(new java.awt.Color(255, 255, 255));
        selectedLocateLabel1.setText("location");

        selectedStopLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedStopLabel1.setForeground(new java.awt.Color(255, 255, 255));
        selectedStopLabel1.setText("88");

        selectedLocateLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedLocateLabel2.setForeground(new java.awt.Color(255, 255, 255));
        selectedLocateLabel2.setText("Location :");

        javax.swing.GroupLayout selectedStopPanelLayout = new javax.swing.GroupLayout(selectedStopPanel);
        selectedStopPanel.setLayout(selectedStopPanelLayout);
        selectedStopPanelLayout.setHorizontalGroup(
            selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedStopPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(selectedStopLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedLocateLabel1)
                    .addComponent(selectedStopLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectedStopPanelLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(selectedLocateLabel2)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );
        selectedStopPanelLayout.setVerticalGroup(
            selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedStopPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedLocateLabel1)
                    .addGroup(selectedStopPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectedStopLabel)
                            .addComponent(selectedStopLabel1))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(selectedStopPanelLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(selectedLocateLabel2)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );

        searchStopsTextField.setBackground(new java.awt.Color(0, 52, 102));
        searchStopsTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        searchStopsTextField.setForeground(new java.awt.Color(255, 255, 255));
        searchStopsTextField.setText("...");
        searchStopsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStopsTextFieldActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 52, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 52, 102));

        departureTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        departureTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        departureTimeLabel.setText("ti:me");

        selectedStopLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedStopLabel3.setForeground(new java.awt.Color(255, 255, 255));
        selectedStopLabel3.setText("Arrival Date:");

        selectedStopLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedStopLabel4.setForeground(new java.awt.Color(255, 255, 255));
        selectedStopLabel4.setText("Departure Date:");

        arrivalTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        arrivalTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        arrivalTimeLabel.setText("ti:me");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedStopLabel4)
                    .addComponent(arrivalTimeLabel)
                    .addComponent(selectedStopLabel3)
                    .addComponent(departureTimeLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedStopLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departureTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(selectedStopLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrivalTimeLabel)
                .addContainerGap())
        );

        selectedLocateLabel.setBackground(new java.awt.Color(0, 0, 0));
        selectedLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedLocateLabel.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(stopsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectedLocateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchStopsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(selectedStopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchStopsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(selectedLocateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectedStopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stopsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchStopsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStopsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchStopsTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentJourney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentJourney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentJourney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentJourney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

      
    }
    private void getJourney() {
        sim.controller.getAPIData();
        
       for(Route route : sim.controller.getRoutes()) {
           if (sim.controller.getSelectedJourney().getRoute_ID().compareTo(route.getRoute_ID()) == 0)
           {
              if (route.getStop_Number().compareTo(1.0) == 0) {
                  for(Station station : sim.controller.getStations()) {
                      if (route.getStation_ID().compareTo(station.getStation_ID()) == 0) 
                          departureStation = station;
                  }
           }
              
                if (route.getStop_Number().compareTo(2.0) == 0) {
                  for(Station station : sim.controller.getStations()) {
                      if (route.getStation_ID().compareTo(station.getStation_ID()) == 0) 
                          previousStation = station;
                  }
           }
                
                if (route.getStop_Number().compareTo(3.0) == 0) {
                  for(Station station : sim.controller.getStations()) {
                      if (route.getStation_ID().compareTo(station.getStation_ID()) == 0) 
                          nextStation = station;
                  }
           }
                
                if (route.getStop_Number().compareTo(4.0) == 0) {
                  for(Station station : sim.controller.getStations()) {
                      if (route.getStation_ID().compareTo(station.getStation_ID()) == 0) 
                          arrivalStation = station;
                  }
           }
           }
       } 
       selectedStation = departureStation;
       
       
    }
    
    private void update() {
    departLocateLabel.setText(departureStation.getStation_Name());
    lastLocateLabel.setText(previousStation.getStation_Name());
    nextLocateLabel.setText(nextStation.getStation_Name());
    arriveLocateLabel.setText(arrivalStation.getStation_Name());
    selectedLocateLabel1.setText(selectedStation.getStation_Name());
    selectedStopLabel1.setText(getStopNumber(selectedStation));       
    departureTimeLabel.setText(sim.controller.getSelectedJourney().getBegin_Time().toString());
    arrivalTimeLabel.setText(sim.controller.getSelectedJourney().getArrival_Time().toString());

    }
    private String getStopNumber(Station station) {
        String stopNumber = "unknown";
       for(Route route : sim.controller.getRoutes()) { 
           if (route.getStation_ID().compareTo(station.getStation_ID()) == 0 && route.getRoute_ID().compareTo(sim.controller.getSelectedJourney().getRoute_ID()) == 0)
           {
               stopNumber =  route.getStop_Number().toString();
           }
       } 
    return stopNumber;
    }
    public class BoxListener extends MouseAdapter
    {
    	public void mouseClicked(MouseEvent me)
    	{
              JPanel clickedBox =(JPanel)me.getSource(); // get the reference to the box that was clicked 
              if (clickedBox == departurePanel) {
                  selectedStation = departureStation;
              }
              
              if (clickedBox == lastPanel) {
                  
               selectedStation = previousStation;
              }
              if (clickedBox == nextPanel){
                  
               selectedStation = nextStation;
              }
              if (clickedBox == arrivePanel){
                  
               selectedStation = arrivalStation;
              }

         update();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrivalLabel;
    private javax.swing.JLabel arrivalTimeLabel;
    private javax.swing.JLabel arriveLocateLabel;
    private javax.swing.JPanel arrivePanel;
    private javax.swing.JLabel departLabel;
    private javax.swing.JLabel departLocateLabel;
    private javax.swing.JPanel departurePanel;
    private javax.swing.JLabel departureTimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JLabel lastLocateLabel;
    private javax.swing.JPanel lastPanel;
    private javax.swing.JLabel nextLabel;
    private javax.swing.JLabel nextLocateLabel;
    private javax.swing.JPanel nextPanel;
    private javax.swing.JTextField searchStopsTextField;
    private javax.swing.JLabel selectedLocateLabel;
    private javax.swing.JLabel selectedLocateLabel1;
    private javax.swing.JLabel selectedLocateLabel2;
    private javax.swing.JLabel selectedStopLabel;
    private javax.swing.JLabel selectedStopLabel1;
    private javax.swing.JLabel selectedStopLabel3;
    private javax.swing.JLabel selectedStopLabel4;
    private javax.swing.JPanel selectedStopPanel;
    private javax.swing.JPanel stopsPanel;
    // End of variables declaration//GEN-END:variables
}
