/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.dataController;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author mstanford
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        getContentPane().setBackground(Color.WHITE); 
        departurePanel.addMouseListener(new BoxListener());
        nextPanel.addMouseListener(new BoxListener());
        arrivePanel.addMouseListener(new BoxListener());
        lastPanel.addMouseListener (new BoxListener());


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stopsPanel = new javax.swing.JPanel();
        departLabel = new javax.swing.JLabel();
        departurePanel = new javax.swing.JPanel();
        departLocateLabel = new javax.swing.JLabel();
        nextLabel = new javax.swing.JLabel();
        arrivalLabel = new javax.swing.JLabel();
        nextPanel = new javax.swing.JPanel();
        nextLocateLabel = new javax.swing.JLabel();
        arrivePanel = new javax.swing.JPanel();
        arriveLocateLabel = new javax.swing.JLabel();
        lastLabel = new javax.swing.JLabel();
        lastPanel = new javax.swing.JPanel();
        lastLocateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectedStopPanel = new javax.swing.JPanel();
        selectedLocateLabel = new javax.swing.JLabel();
        selectedBoardingLabel = new javax.swing.JLabel();
        selectedDisembarkingLabel = new javax.swing.JLabel();
        selectedStopLabel = new javax.swing.JLabel();
        selectedTimeLabel1 = new javax.swing.JLabel();
        selectedLocateLabel1 = new javax.swing.JLabel();
        selectedBoardingLabel1 = new javax.swing.JLabel();
        selectedDisembarkingLabel1 = new javax.swing.JLabel();
        selectedStopLabel1 = new javax.swing.JLabel();
        selectedTimeLabel2 = new javax.swing.JLabel();
        searchStopsTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        stopsPanel.setBackground(new java.awt.Color(0, 52, 102));

        departLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        departLabel.setForeground(new java.awt.Color(255, 255, 255));
        departLabel.setText("Departure");

        departurePanel.setBackground(new java.awt.Color(255, 255, 255));

        departLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        departLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        departLocateLabel.setText("Location");
        departLocateLabel.setToolTipText("");

        javax.swing.GroupLayout departurePanelLayout = new javax.swing.GroupLayout(departurePanel);
        departurePanel.setLayout(departurePanelLayout);
        departurePanelLayout.setHorizontalGroup(
            departurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departurePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(departLocateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        departurePanelLayout.setVerticalGroup(
            departurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departurePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(departLocateLabel)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        nextLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nextLabel.setForeground(new java.awt.Color(255, 255, 255));
        nextLabel.setText("Next");

        arrivalLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        arrivalLabel.setForeground(new java.awt.Color(255, 255, 255));
        arrivalLabel.setText("Arrival");

        nextPanel.setBackground(new java.awt.Color(255, 255, 255));
        nextPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        nextLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nextLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        nextLocateLabel.setText("Location");
        nextLocateLabel.setToolTipText("");

        javax.swing.GroupLayout nextPanelLayout = new javax.swing.GroupLayout(nextPanel);
        nextPanel.setLayout(nextPanelLayout);
        nextPanelLayout.setHorizontalGroup(
            nextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nextLocateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nextPanelLayout.setVerticalGroup(
            nextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nextLocateLabel)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        arrivePanel.setBackground(new java.awt.Color(255, 255, 255));
        arrivePanel.setPreferredSize(new java.awt.Dimension(150, 150));

        arriveLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        arriveLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        arriveLocateLabel.setText("Location");
        arriveLocateLabel.setToolTipText("");

        javax.swing.GroupLayout arrivePanelLayout = new javax.swing.GroupLayout(arrivePanel);
        arrivePanel.setLayout(arrivePanelLayout);
        arrivePanelLayout.setHorizontalGroup(
            arrivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arriveLocateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        arrivePanelLayout.setVerticalGroup(
            arrivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arriveLocateLabel)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        lastLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lastLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastLabel.setText("Last");

        lastPanel.setBackground(new java.awt.Color(255, 255, 255));
        lastPanel.setPreferredSize(new java.awt.Dimension(150, 150));

        lastLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lastLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        lastLocateLabel.setText("Location");
        lastLocateLabel.setToolTipText("");

        javax.swing.GroupLayout lastPanelLayout = new javax.swing.GroupLayout(lastPanel);
        lastPanel.setLayout(lastPanelLayout);
        lastPanelLayout.setHorizontalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastLocateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lastPanelLayout.setVerticalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastLocateLabel)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout stopsPanelLayout = new javax.swing.GroupLayout(stopsPanel);
        stopsPanel.setLayout(stopsPanelLayout);
        stopsPanelLayout.setHorizontalGroup(
            stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departurePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departLabel))
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(lastPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lastLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addComponent(nextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopsPanelLayout.createSequentialGroup()
                        .addComponent(nextLabel)
                        .addGap(72, 72, 72)))
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopsPanelLayout.createSequentialGroup()
                        .addComponent(arrivalLabel)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopsPanelLayout.createSequentialGroup()
                        .addComponent(arrivePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        stopsPanelLayout.setVerticalGroup(
            stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopsPanelLayout.createSequentialGroup()
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stopsPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(departLabel)
                                    .addComponent(arrivalLabel))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nextLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departurePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrivePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lastLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        departurePanel.getAccessibleContext().setAccessibleName("Depart");
        nextPanel.getAccessibleContext().setAccessibleName("Next");
        arrivePanel.getAccessibleContext().setAccessibleName("Arrive");
        lastPanel.getAccessibleContext().setAccessibleName("Last");

        selectedStopPanel.setBackground(new java.awt.Color(0, 52, 102));

        selectedLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedLocateLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectedLocateLabel.setText("Location :");

        selectedBoardingLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedBoardingLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectedBoardingLabel.setText("Total Passengers :");

        selectedDisembarkingLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedDisembarkingLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectedDisembarkingLabel.setText("Change :");

        selectedStopLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedStopLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectedStopLabel.setText("Stop Num:");

        selectedTimeLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedTimeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        selectedTimeLabel1.setText("Time:");

        selectedLocateLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedLocateLabel1.setForeground(new java.awt.Color(255, 255, 255));
        selectedLocateLabel1.setText("location");

        selectedBoardingLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedBoardingLabel1.setForeground(new java.awt.Color(255, 255, 255));
        selectedBoardingLabel1.setText("44");

        selectedDisembarkingLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedDisembarkingLabel1.setForeground(new java.awt.Color(255, 255, 255));
        selectedDisembarkingLabel1.setText("+16");

        selectedStopLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedStopLabel1.setForeground(new java.awt.Color(255, 255, 255));
        selectedStopLabel1.setText("88");

        selectedTimeLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedTimeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        selectedTimeLabel2.setText("ti:me");

        javax.swing.GroupLayout selectedStopPanelLayout = new javax.swing.GroupLayout(selectedStopPanel);
        selectedStopPanel.setLayout(selectedStopPanelLayout);
        selectedStopPanelLayout.setHorizontalGroup(
            selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedStopPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectedStopLabel)
                    .addComponent(selectedTimeLabel1)
                    .addComponent(selectedLocateLabel)
                    .addComponent(selectedDisembarkingLabel)
                    .addComponent(selectedBoardingLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectedStopLabel1)
                    .addComponent(selectedTimeLabel2)
                    .addComponent(selectedLocateLabel1)
                    .addComponent(selectedDisembarkingLabel1)
                    .addComponent(selectedBoardingLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selectedStopPanelLayout.setVerticalGroup(
            selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedStopPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectedStopPanelLayout.createSequentialGroup()
                        .addComponent(selectedLocateLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedTimeLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedStopLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedBoardingLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectedDisembarkingLabel1))
                    .addGroup(selectedStopPanelLayout.createSequentialGroup()
                        .addComponent(selectedLocateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedTimeLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedStopLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectedBoardingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectedDisembarkingLabel)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        searchStopsTextField.setBackground(new java.awt.Color(0, 52, 102));
        searchStopsTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        searchStopsTextField.setForeground(new java.awt.Color(255, 255, 255));
        searchStopsTextField.setText("...");

        jButton1.setBackground(new java.awt.Color(0, 52, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(selectedStopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stopsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchStopsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(181, 181, 181)))
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(stopsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchStopsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addComponent(selectedStopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        selectedLocateLabel1.setText(searchStopsTextField.getText());

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(false);
            }
        });

    }
    
    public class BoxListener extends MouseAdapter
    {
    	public void mouseClicked(MouseEvent me)
    	{
              JPanel clickedBox =(JPanel)me.getSource(); // get the reference to the box that was clicked 
              selectedLocateLabel1.setText(clickedBox.getAccessibleContext().getAccessibleName());

             
              // insert here the code defining what happens when a grid is clicked
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrivalLabel;
    private javax.swing.JLabel arriveLocateLabel;
    private javax.swing.JPanel arrivePanel;
    private javax.swing.JLabel departLabel;
    private javax.swing.JLabel departLocateLabel;
    private javax.swing.JPanel departurePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JLabel lastLocateLabel;
    private javax.swing.JPanel lastPanel;
    private javax.swing.JLabel nextLabel;
    private javax.swing.JLabel nextLocateLabel;
    private javax.swing.JPanel nextPanel;
    private javax.swing.JTextField searchStopsTextField;
    private javax.swing.JLabel selectedBoardingLabel;
    private javax.swing.JLabel selectedBoardingLabel1;
    private javax.swing.JLabel selectedDisembarkingLabel;
    private javax.swing.JLabel selectedDisembarkingLabel1;
    private javax.swing.JLabel selectedLocateLabel;
    private javax.swing.JLabel selectedLocateLabel1;
    private javax.swing.JLabel selectedStopLabel;
    private javax.swing.JLabel selectedStopLabel1;
    private javax.swing.JPanel selectedStopPanel;
    private javax.swing.JLabel selectedTimeLabel1;
    private javax.swing.JLabel selectedTimeLabel2;
    private javax.swing.JPanel stopsPanel;
    // End of variables declaration//GEN-END:variables
}
