/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import data.dataController;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import main.sim;

/**
 *
 * @author mstanford
 */
public class Journey extends javax.swing.JFrame {
    /**
     * Creates new form Home
     */
    public Journey() {
        initComponents();
        tblJourneys.setRowHeight(tblJourneys.getRowHeight() + 15);
        tblJobs.setRowHeight(tblJobs.getRowHeight() + 30);
        tblJourneys.getTableHeader().setFont(tblJourneys.getTableHeader().getFont().deriveFont(30f));
        tblJobs.getTableHeader().setFont(tblJobs.getTableHeader().getFont().deriveFont(30f));
        Update();
        this.tblJourneys.setAutoCreateRowSorter(true);
        this.tblJobs.setAutoCreateRowSorter(true);
        getContentPane().setBackground(Color.WHITE); 
        departurePanel.addMouseListener(new BoxListener());
        arrivePanel.addMouseListener(new BoxListener());
        pnlDepartDate.addMouseListener (new BoxListener());


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stopsPanel = new javax.swing.JPanel();
        departLabel = new javax.swing.JLabel();
        departurePanel = new javax.swing.JPanel();
        departLocateLabel = new javax.swing.JLabel();
        arrivalLabel = new javax.swing.JLabel();
        arrivePanel = new javax.swing.JPanel();
        arriveLocateLabel = new javax.swing.JLabel();
        lblDepartureDate = new javax.swing.JLabel();
        pnlDepartDate = new javax.swing.JPanel();
        lblDisDepartDate = new javax.swing.JLabel();
        lblArrivalDate = new javax.swing.JLabel();
        pnlArrivalDate = new javax.swing.JPanel();
        lblDisArrivalDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectedStopPanel = new javax.swing.JPanel();
        selectedLocateLabel = new javax.swing.JLabel();
        lblStopsAt = new javax.swing.JLabel();
        lblJourneyName = new javax.swing.JLabel();
        lblDisStopsAt = new javax.swing.JLabel();
        txtSearchJourney = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblOnDay1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJourneys = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJobs = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnJobComplete = new javax.swing.JButton();
        txtJobId = new javax.swing.JTextField();
        lblUserGreeting = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        stopsPanel.setBackground(new java.awt.Color(0, 52, 102));

        departLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        departLabel.setForeground(new java.awt.Color(255, 255, 255));
        departLabel.setText("Departure");

        departurePanel.setBackground(new java.awt.Color(255, 255, 255));
        departurePanel.setMinimumSize(new java.awt.Dimension(164, 155));

        departLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        departLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        departLocateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departLocateLabel.setText("N/A");
        departLocateLabel.setToolTipText("");

        javax.swing.GroupLayout departurePanelLayout = new javax.swing.GroupLayout(departurePanel);
        departurePanel.setLayout(departurePanelLayout);
        departurePanelLayout.setHorizontalGroup(
            departurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departurePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(departLocateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        departurePanelLayout.setVerticalGroup(
            departurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(departurePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(departLocateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        arrivalLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        arrivalLabel.setForeground(new java.awt.Color(255, 255, 255));
        arrivalLabel.setText("Arrival");

        arrivePanel.setBackground(new java.awt.Color(255, 255, 255));
        arrivePanel.setPreferredSize(new java.awt.Dimension(150, 150));

        arriveLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        arriveLocateLabel.setForeground(new java.awt.Color(0, 52, 102));
        arriveLocateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arriveLocateLabel.setText("N/A");
        arriveLocateLabel.setToolTipText("");

        javax.swing.GroupLayout arrivePanelLayout = new javax.swing.GroupLayout(arrivePanel);
        arrivePanel.setLayout(arrivePanelLayout);
        arrivePanelLayout.setHorizontalGroup(
            arrivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arriveLocateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        arrivePanelLayout.setVerticalGroup(
            arrivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arrivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arriveLocateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblDepartureDate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblDepartureDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartureDate.setText("Departure Date");

        pnlDepartDate.setBackground(new java.awt.Color(255, 255, 255));
        pnlDepartDate.setPreferredSize(new java.awt.Dimension(150, 150));

        lblDisDepartDate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblDisDepartDate.setForeground(new java.awt.Color(0, 52, 102));
        lblDisDepartDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisDepartDate.setText("N/A");
        lblDisDepartDate.setToolTipText("");

        javax.swing.GroupLayout pnlDepartDateLayout = new javax.swing.GroupLayout(pnlDepartDate);
        pnlDepartDate.setLayout(pnlDepartDateLayout);
        pnlDepartDateLayout.setHorizontalGroup(
            pnlDepartDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisDepartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDepartDateLayout.setVerticalGroup(
            pnlDepartDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartDateLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblDisDepartDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblArrivalDate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblArrivalDate.setForeground(new java.awt.Color(255, 255, 255));
        lblArrivalDate.setText("Arrival Date");

        pnlArrivalDate.setBackground(new java.awt.Color(255, 255, 255));
        pnlArrivalDate.setPreferredSize(new java.awt.Dimension(150, 150));

        lblDisArrivalDate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblDisArrivalDate.setForeground(new java.awt.Color(0, 52, 102));
        lblDisArrivalDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisArrivalDate.setText("N/A");
        lblDisArrivalDate.setToolTipText("");

        javax.swing.GroupLayout pnlArrivalDateLayout = new javax.swing.GroupLayout(pnlArrivalDate);
        pnlArrivalDate.setLayout(pnlArrivalDateLayout);
        pnlArrivalDateLayout.setHorizontalGroup(
            pnlArrivalDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArrivalDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisArrivalDate, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlArrivalDateLayout.setVerticalGroup(
            pnlArrivalDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArrivalDateLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblDisArrivalDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout stopsPanelLayout = new javax.swing.GroupLayout(stopsPanel);
        stopsPanel.setLayout(stopsPanelLayout);
        stopsPanelLayout.setHorizontalGroup(
            stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departurePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(departLabel)))
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopsPanelLayout.createSequentialGroup()
                                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlDepartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopsPanelLayout.createSequentialGroup()
                                .addComponent(lblArrivalDate)
                                .addGap(88, 88, 88))))
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblDepartureDate)))
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(arrivalLabel)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopsPanelLayout.createSequentialGroup()
                        .addComponent(arrivePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        stopsPanelLayout.setVerticalGroup(
            stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopsPanelLayout.createSequentialGroup()
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departLabel)
                            .addComponent(arrivalLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDepartureDate)))
                .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(stopsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(arrivePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(departurePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(stopsPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(pnlDepartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblArrivalDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(pnlArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        departurePanel.getAccessibleContext().setAccessibleName("Depart");
        arrivePanel.getAccessibleContext().setAccessibleName("Arrive");
        pnlDepartDate.getAccessibleContext().setAccessibleName("Last");

        selectedStopPanel.setBackground(new java.awt.Color(0, 52, 102));

        selectedLocateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        selectedLocateLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectedLocateLabel.setText("Route Name :");

        lblStopsAt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblStopsAt.setForeground(new java.awt.Color(255, 255, 255));
        lblStopsAt.setText("Stops at:");

        lblJourneyName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblJourneyName.setForeground(new java.awt.Color(255, 255, 255));
        lblJourneyName.setText("N/A");

        lblDisStopsAt.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblDisStopsAt.setForeground(new java.awt.Color(255, 255, 255));
        lblDisStopsAt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDisStopsAt.setText("N/A");
        lblDisStopsAt.setToolTipText("");
        lblDisStopsAt.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDisStopsAt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout selectedStopPanelLayout = new javax.swing.GroupLayout(selectedStopPanel);
        selectedStopPanel.setLayout(selectedStopPanelLayout);
        selectedStopPanelLayout.setHorizontalGroup(
            selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedStopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectedStopPanelLayout.createSequentialGroup()
                        .addComponent(selectedLocateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJourneyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(selectedStopPanelLayout.createSequentialGroup()
                        .addComponent(lblStopsAt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDisStopsAt, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        selectedStopPanelLayout.setVerticalGroup(
            selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedStopPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJourneyName)
                    .addComponent(selectedLocateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(selectedStopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStopsAt)
                    .addComponent(lblDisStopsAt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        txtSearchJourney.setBackground(new java.awt.Color(0, 52, 102));
        txtSearchJourney.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtSearchJourney.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchJourney.setText("...");
        txtSearchJourney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchJourneyMouseClicked(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 52, 102));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Search for a Journey:");

        lblOnDay1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblOnDay1.setForeground(new java.awt.Color(51, 51, 51));
        lblOnDay1.setText("Journey ID:");

        tblJourneys.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblJourneys.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Journey_ID", "Route", "Base Price", "Departure", "Time Delay", "Delay Reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJourneys.setRowHeight(40);
        tblJourneys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJourneysMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJourneys);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Future Journeys:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Job_ID to mark as complete:");

        tblJobs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job ID", "Description", "Deadline", "Journey ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJobsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblJobs);

        btnLogout.setBackground(new java.awt.Color(0, 52, 102));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAccount.setBackground(new java.awt.Color(0, 52, 102));
        btnAccount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnAccount.setText("Account");
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        btnJobComplete.setBackground(new java.awt.Color(0, 52, 102));
        btnJobComplete.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnJobComplete.setForeground(new java.awt.Color(255, 255, 255));
        btnJobComplete.setText("Job Complete");
        btnJobComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobCompleteActionPerformed(evt);
            }
        });

        txtJobId.setBackground(new java.awt.Color(0, 52, 102));
        txtJobId.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtJobId.setForeground(new java.awt.Color(255, 255, 255));
        txtJobId.setText("...");
        txtJobId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJobIdMouseClicked(evt);
            }
        });

        lblUserGreeting.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUserGreeting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserGreeting.setText("Hello <UserRank> <user>, Your Jobs are Below:");

        btnRefresh.setBackground(new java.awt.Color(0, 52, 102));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh Tables");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnJobComplete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJobId, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblOnDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchJourney, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(stopsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectedStopPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUserGreeting, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE))
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stopsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchJourney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOnDay1)
                            .addComponent(btnSearch))
                        .addGap(18, 18, 18)
                        .addComponent(selectedStopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUserGreeting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtJobId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnJobComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLogout)
                                    .addComponent(btnAccount)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel1))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
                DisplayResults();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void DisplayResults(){
        //Display journey data
        String s = sim.controller.SQLInjectionCheck(txtSearchJourney.getText());
        sim.controller.findJourney(s);
        DateFormat timeFormat = new SimpleDateFormat("K:mm a"); 
        DateFormat dateFormat = new SimpleDateFormat("dd:MM:yyyy"); 
        String strDate = timeFormat.format(sim.controller.getSelectedJourney().getBegin_Time()); 
        this.departLocateLabel.setText(strDate);
        strDate = dateFormat.format(sim.controller.getSelectedJourney().getBegin_Time());
        this.lblDisDepartDate.setText(strDate);
        strDate = timeFormat.format(sim.controller.getSelectedJourney().getArrival_Time());
        this.arriveLocateLabel.setText(strDate);
        strDate =dateFormat.format(sim.controller.getSelectedJourney().getArrival_Time());
        this.lblDisArrivalDate.setText(strDate);
        
        //Display route information
        sim.controller.FindRoute_Num((int) Math.floor(sim.controller.getSelectedJourney().getRoute_ID()));
        this.lblJourneyName.setText(sim.controller.getSelectedRoute_Num().getRoute_Name());
        
        //Station stops information
        this.lblDisStopsAt.setText(sim.controller.FindStopNames((int) Math.floor(sim.controller.getSelectedJourney().getRoute_ID())));
    }
    private void txtSearchJourneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchJourneyMouseClicked
        this.txtSearchJourney.setText("");
    }//GEN-LAST:event_txtSearchJourneyMouseClicked

    private void tblJourneysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJourneysMouseClicked
        String Journey_ID = tblJourneys.getValueAt(tblJourneys.getSelectedRow(), 0).toString();
        this.txtSearchJourney.setText(Journey_ID);
        DisplayResults();
    }//GEN-LAST:event_tblJourneysMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        sim.controller.setCurrentUser(null);
        Login view = new Login();
        view.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        this.dispose();
        Account_Settings view = new Account_Settings();
        view.setVisible(true);
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnJobCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobCompleteActionPerformed
       sim.controller.PutJobComplete(Integer.parseInt(sim.controller.SQLInjectionCheck(this.txtJobId.getText())));
       Update();
    }//GEN-LAST:event_btnJobCompleteActionPerformed

    private void txtJobIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJobIdMouseClicked
        this.txtJobId.setText("");
    }//GEN-LAST:event_txtJobIdMouseClicked

    private void tblJobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJobsMouseClicked
            String Job_ID = tblJobs.getValueAt(tblJobs.getSelectedRow(), 0).toString();
            this.txtJobId.setText(Job_ID);
    }//GEN-LAST:event_tblJobsMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Update();
    }//GEN-LAST:event_btnRefreshActionPerformed

    
    private void Update(){
       //Clear journey table
        DefaultTableModel table = (DefaultTableModel)tblJourneys.getModel();
        table.getDataVector().removeAllElements();
        table.fireTableDataChanged();
        
        //clear job tbale
        table = (DefaultTableModel)tblJobs.getModel();
        table.getDataVector().removeAllElements();
        table.fireTableDataChanged();
        
        

        
        sim.controller.GetAllJourneys();
        sim.controller.GetUsersJobs();
        this.lblUserGreeting.setText("Hello " + sim.controller.getCurrentUser().getUser_Rank()
                + " " + sim.controller.getCurrentUser().getFirst_Name() + ", Your Jobs are Below:");
        DefaultTableModel journeyModel = (DefaultTableModel) tblJourneys.getModel();
        DefaultTableModel jobModel = (DefaultTableModel) tblJobs.getModel();
        
        
        for (int j = 0; j < sim.controller.getJourneys().size(); j++){
            sim.controller.FindRoute_Num((int) Math.round(sim.controller.getJourneys().get(j).getRoute_ID()));
            journeyModel.insertRow(journeyModel.getRowCount(), new Object[]{((int) Math.round(sim.controller.getJourneys().get(j).getJourney_ID())),
                    sim.controller.getSelectedRoute_Num().getRoute_Name(),
                    "£" + sim.controller.getJourneys().get(j).getBase_Price(),
                    sim.controller.getJourneys().get(j).getBegin_Time(),
                    sim.controller.getJourneys().get(j).getTime_Delay(),
                    sim.controller.getJourneys().get(j).getDelay_Reason()});
            }
        
        for (int m = 0; m < sim.controller.getJobs().size(); m++){
            jobModel.insertRow(jobModel.getRowCount(), new Object[]{((int) Math.round(sim.controller.getJobs().get(m).getJob_ID())),
                    sim.controller.getJobs().get(m).getJob_Description(),
                    sim.controller.getJobs().get(m).getJob_Date(),
                    sim.controller.getJobs().get(m).getJourney_ID()});
            }
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }
    
    public class BoxListener extends MouseAdapter
    {
    	public void mouseClicked(MouseEvent me)
    	{
              JPanel clickedBox =(JPanel)me.getSource(); // get the reference to the box that was clicked 
              lblJourneyName.setText(clickedBox.getAccessibleContext().getAccessibleName());

             
              // insert here the code defining what happens when a grid is clicked
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrivalLabel;
    private javax.swing.JLabel arriveLocateLabel;
    private javax.swing.JPanel arrivePanel;
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnJobComplete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel departLabel;
    private javax.swing.JLabel departLocateLabel;
    private javax.swing.JPanel departurePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArrivalDate;
    private javax.swing.JLabel lblDepartureDate;
    private javax.swing.JLabel lblDisArrivalDate;
    private javax.swing.JLabel lblDisDepartDate;
    private javax.swing.JLabel lblDisStopsAt;
    private javax.swing.JLabel lblJourneyName;
    private javax.swing.JLabel lblOnDay1;
    private javax.swing.JLabel lblStopsAt;
    private javax.swing.JLabel lblUserGreeting;
    private javax.swing.JPanel pnlArrivalDate;
    private javax.swing.JPanel pnlDepartDate;
    private javax.swing.JLabel selectedLocateLabel;
    private javax.swing.JPanel selectedStopPanel;
    private javax.swing.JPanel stopsPanel;
    private javax.swing.JTable tblJobs;
    private javax.swing.JTable tblJourneys;
    private javax.swing.JTextField txtJobId;
    private javax.swing.JTextField txtSearchJourney;
    // End of variables declaration//GEN-END:variables
}
