//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRCS251A_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public decimal BOOKING_ID { get; set; }
        public decimal JOURNEY_ID { get; set; }
        public decimal USER_ID { get; set; }
        public string BOOKING_CODE { get; set; }
    }
}
