//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRCS251A_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTE
    {
        public decimal ROUTE_ID { get; set; }
        public decimal STATION_ID { get; set; }
        public decimal STOP_NUMBER { get; set; }
    }
}
