//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRCS251A_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATION
    {
        public decimal STATION_ID { get; set; }
        public string STATION_TYPE { get; set; }
        public string STATION_NAME { get; set; }
        public string S_ADDRESS_LINE_1 { get; set; }
        public string S_ADDRESS_LINE_2 { get; set; }
        public string S_POSTCODE { get; set; }
    }
}
