//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRCS251A_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION_LOG
    {
        public decimal TRANSACTION_ID { get; set; }
        public string CARD_LAST_DIGITS { get; set; }
        public System.DateTime TIME_OF_TRANSACTION { get; set; }
        public decimal TRANSACTION_COST { get; set; }
    }
}
