//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRCS251A_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACCOUNT
    {
        public decimal USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_RANK { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime DATE_OF_BIRTH { get; set; }
        public string U_ADDRESS_LINE_1 { get; set; }
        public string U_ADDRESS_LINE_2 { get; set; }
        public string U_POSTCODE { get; set; }
        public string U_TOWN { get; set; }
        public string EMAIL { get; set; }
        public string CONTACT_NUMBER { get; set; }
        public string ALTERNATIVE_NUMBER { get; set; }
        public string MARKETING_OPT_IN { get; set; }
    }
}
