//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRCS251A_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE
    {
        public string VEHICLE_REG { get; set; }
        public Nullable<decimal> JOURNEY_ID { get; set; }
        public decimal P_CAPACITY { get; set; }
        public string STORED_LOCATION { get; set; }
        public string VEHICLE_TYPE { get; set; }
    }
}
